
### Django命令

创建项目：
	django-admin startproject project_name
	
查看manage.py 有那些命令可用
	python manage.py  help

启动项目：
	python manage.py runserver

数据库迁移
	python manage.py makemigrations
	python manage.py migrate
	
创建超级管理员
	python manage.py  createsuperuser
	
创建应用
	python manage.py startapp app_name
	
创建缓存表
	python manage.py createcachetable
	
搜集静态文件
	python manage.py collectstatic # 搜集到settings文件的STATIC_ROOT路径下

	
### Django知识点
1. urls.py
	
	访问路径配置：
	
		2.x 使用的path,正则表达式使用re_path;
							
		1.x 使用的版本是url，
		
2. 访问admin之前要先迁移数据库，否则会提示：no such table: django_session等

	python manage.py makemigrations
	
	python manage.py migrate
	
3. 访问基本流程

	urls文件里面的路径 ------------------->views文件里面的方法------------------->前端页面
	
4. 添加静态文件

	{% load staticfiles %}
	STATICFILES_DIRS = [os.path.join(BASE_DIR,'static'),]
	
5. get_object_or_404()
	article = get_object_or_404(Article,pk=article_pk) # 注意使用方法，**不是**通过Article.objects.get_object_or_404
	
6. django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.

		解决方法：在 对应模块__init__.py文件中添加以下代码即可。
		import pymysql
		pymysql.install_as_MySQLdb()
		[参考](https://blog.csdn.net/LHYzyp/article/details/70550683)
		
7. 在定义模型的时候，字段类型后面要加括号，不然在迁移到数据库的时候，不会创建对应的字段

8. RuntimeWarning: DateTimeField TaoBaoProject.begin_date received a naive datetime (2017-11-28 00:00:00) while time zone support is active. RuntimeWarning)

	最简单的方式是：修改settings文件中USE_TZ 为 False，但是这样的话，应该关闭了其他功能，具体到[官网查看](https://docs.djangoproject.com/en/2.0/topics/i18n/timezones/)
	
9. Cannot add or update a child row: a foreign key constraint fails 

		 # 这里数据库默认使用关联对象的主键,如果是其他字段，需要设置to_field ,并且关联对象的对应字段设置unique=True
		project = models.ForeignKey(TaoBaoProject,on_delete=models.CASCADE,to_field='original_id')
	
10. invalid literal for int() with base 10: ''

		由于int()转换值的时候，传入值为空字符串
		
11.HTTPSConnectionPool(host='youpin.mi.com', port=443): Max retries exceeded with url: /app/shop/pipe (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B7D86D0908>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))


12. ValueError: Invalid control character at: line 1 column 33 (char 33)

13. json.decoder.JSONDecodeError: Invalid \escape: line 223 column 51 (char 14792)
	
		json字符串解析异常
		解决方式：https://stackoverflow.com/questions/43018576/valueerror-invalid-escape-when-readin-json-as-respons-in-scrapy
		
		
		
### Python 知识点

同一个目录，引用用.代替

导包顺序：Python自带包---->第三方包----->自己的包

生成requirements.txt:   pip freeze > requirements.txt